### ISSUE TITLE
Avoid downloading "virtual" interversion extension packages

### ISSUE THREAD

**Issue by cmoesel** [gematik/codfsh#13]
SUSHI requires users to indicate they are using "interversion" extensions by declaring an interversion extension package as a dependency. These package names can be `hl7.fhir.extensions.r2`, `hl7.fhir.extensions.r3`, `hl7.fhir.extensions.r4`, or `hl7.fhir.extensions.r5`, as shown at the bottom of [this section](https://hl7.org/fhir/versions.html#extensions) in the spec.

These packages do not actually exist. SUSHI treats them as virtual packages, generating necessary contents on-the-fly. As such, this extension should ignore these packages when it attempts to download dependencies -- because the download will fail every time.

Grahame may create real interversion packages some day, but it's not clear when (and it's already been a while).

**Comment by alexzautke** [comment]
+1 This issue was the first issue that I ran into in my projects while trying out the extension.

**Comment by SvenSommer** [comment]
Hi @cmoesel,

I'm pleased to inform you that the fix has been implemented and merged into the main branch. The extension will now ignore "virtual" interversion packages when it attempts to download dependencies.

The changes are part of version "1.0.7" of our extension. Please update to this version or higher to see the improvements.

Please don't hesitate to test it out and let us know if you encounter any other issues or have more suggestions.

Best,
Robert
