### ISSUE TITLE
Document Generate Snapshots configuration option

### ISSUE THREAD

**Issue by cmoesel** [gematik/codfsh#14]
It would be helpful to have some documentation indicating what the "Generate Snapshots" config does. My guess is that if it downloads a package that doesn't have snapshots, it will use firely terminal or the validator to generate the snapshots in the cached package. Is that right?

**Comment by patrick-werner** [comment]
I think it is only a wrapper for sushi:
  -s, --snapshot           generate snapshot in Structure Definition output (default: false)

**Comment by cmoesel** [comment]
Oh right. I forgot that we even have that option in SUSHI! Good call...
