### ISSUE TITLE
sushi should be called with double quotes around the path

### ISSUE THREAD

**Issue by alexzautke** [gematik/codfsh#18]
In my case I had a whitespace within the path of the SUSHI project, which results in an invalid interpretation of the path:

```
sushi /Users/alex/Dev/FHIR Profiling/gematik/spec-E-Rechnung/Resources/
info  Running SUSHI v3.0.0 (implements FHIR Shorthand specification v2.0.0)

info  Arguments:

info    /Users/alex/Dev/FHIR

info  No output path specified. Output to /Users/alex/Dev/FHIR

info  No FSH files or sushi-config.yaml present.

child process exited with code 0
```

If you put double-quotes around the path, e.g. calling sushi via

```
sushi "/Users/alex/Dev/FHIR Profiling/gematik/spec-E-Rechnung/Resources/"
```

it works as expected

**Comment by SvenSommer** [comment]
Hi @alexzautke,

Thanks for bringing this issue to our attention. I'm pleased to report that I've implemented a fix for the issue you raised with https://github.com/gematik/codfsh/commit/395397add8e5f47932d00f0e47e25f9cce53bd1a. The path now gets wrapped in double quotes to handle any whitespace correctly. This should resolve the problems you were experiencing.

I've thoroughly tested the fix and it seems to handle paths with whitespaces as expected. The fix has been merged into the main branch and is now part of version "1.0.6" of our extension. Please update to this version or higher to experience the improvements.

I encourage you to test it out and see if it resolves the issue on your end. Please don't hesitate to reach out if you have further issues or suggestions. Your feedback is immensely helpful in improving our project.

Best,
Robert
