### ISSUE TITLE
Additional QualityCheck

### ISSUE THREAD

**Issue by HendrikGematik** [gematik/codfsh#4]
firely terminal supports kind of validation:https://docs.fire.ly/projects/Firely-Terminal/Quality-Control.html 
add `fhir check` to sushi run/build

**Comment by SvenSommer** [comment]
Seems like this feature is only available with a paid licence:
```
% fhir check

For this feature, you have to be logged in with an active license.
See http://simplifier.net/pricing
You can use the login command to login.
Without a license you can still run 'fhir check free'
```

This is a possible feature for the future if users request it or if we have used it and are convinced of its necessity.
For now I would not see it as a feature in the near future.
